# Generated by Django 3.2.12 on 2022-02-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('navigation1', models.CharField(blank=True, max_length=100, null=True)),
                ('navigation2', models.CharField(blank=True, max_length=100, null=True)),
                ('footerheading', models.CharField(blank=True, max_length=100, null=True)),
                ('footer1', models.CharField(blank=True, max_length=100, null=True)),
                ('footer2', models.CharField(blank=True, max_length=100, null=True)),
                ('footer3', models.CharField(blank=True, max_length=100, null=True)),
                ('herotitle', models.TextField(blank=True, null=True)),
                ('herotext1', models.TextField(blank=True, null=True)),
                ('herotext2', models.TextField(blank=True, null=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('middletitle', models.CharField(blank=True, max_length=100, null=True)),
                ('middletext', models.TextField(blank=True, null=True)),
                ('middletitle1', models.CharField(blank=True, max_length=100, null=True)),
                ('middletext1', models.TextField(blank=True, null=True)),
                ('endtext', models.CharField(blank=True, max_length=100, null=True)),
                ('endemail', models.CharField(blank=True, max_length=100, null=True)),
                ('contactme', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
