# Generated by Django 3.2.12 on 2022-02-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderNav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('navigation1', models.CharField(blank=True, max_length=100, null=True)),
                ('navigation2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
