# Generated by Django 3.2.11 on 2022-02-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_footernav'),
    ]

    operations = [
        migrations.CreateModel(
            name='herosection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herotitle', models.TextField(blank=True, null=True)),
                ('herotext1', models.TextField(blank=True, null=True)),
                ('herotext2', models.TextField(blank=True, null=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
