# Generated by Django 3.2.11 on 2022-02-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_herosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroMiddleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middletitle', models.CharField(blank=True, max_length=100, null=True)),
                ('middletext', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
