# Generated by Django 3.2.11 on 2022-02-03 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_heromiddlesection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='herosection',
            new_name='HeroHeadSection',
        ),
    ]
