# Generated by Django 3.2.11 on 2022-02-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_rename_herosection_heroheadsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroEndSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endtext', models.CharField(blank=True, max_length=100, null=True)),
                ('endemail', models.CharField(blank=True, max_length=100, null=True)),
                ('contactme', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
