# Generated by Django 3.2.11 on 2022-02-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('blogimage', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
